# Generated by Django 4.2.21 on 2025-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_casestudy_question_case_study_submisson_case_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="case_studies/"),
        ),
    ]
